# Generated by Django 4.1.5 on 2023-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePrefix', models.CharField(default='Mr.', max_length=4)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('middleName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='someone123@gmail.com', max_length=256)),
                ('phoneNumber', models.BigIntegerField(default=9999999999)),
                ('alternatePhoneNumber', models.BigIntegerField(default=9999999999)),
                ('address', models.CharField(default='999_999_999_9', max_length=256)),
                ('motherName', models.CharField(default='', max_length=50)),
                ('fatherName', models.CharField(default='', max_length=50)),
                ('zipCode', models.IntegerField(default=800000)),
                ('dateOfBirth', models.DateField(default=0)),
                ('panNumber', models.CharField(default='AXXXXXXXXX', max_length=10)),
                ('aadhaarNumber', models.BigIntegerField(default='999_999_999_999')),
                ('occupation', models.CharField(default='', max_length=50)),
                ('relation', models.CharField(default='', max_length=50)),
                ('accountType', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
