# Generated by Django 4.1.5 on 2023-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dateOfBirth',
            field=models.DateField(default='1905-01-01'),
        ),
    ]
