# Generated by Django 4.1.5 on 2023-01-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='accountNumber',
        ),
    ]
