# Generated by Django 4.1.5 on 2023-01-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_account_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
