# Generated by Django 4.1.5 on 2023-01-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fromAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromAccountId', to='home.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toAccountId', to='home.account'),
        ),
    ]
